### PR TITLE
#280: Adds test scaffolding and codecov.io integration

### PR DESCRIPTION
**Pull request by bryjbrown**
This PR includes all the changes from https://github.com/Islandora-CLAW/pdx/pull/9 plus an update to .travis.yml suggested in https://github.com/Islandora-CLAW/pdx/pull/9#issuecomment-229141101.

### CODE REVIEW

**Comment by whikloj** [comment]
PSR problems @bryjbrown.

From the PDX directory if you run
`php vendor/bin/phpcs --standard=PSR2 src test`

it will show you all the errors, and if you run

`php vendor/bin/phpcbf --standard=PSR2 src test`

it will automatically fix all that it can.

**Comment by bryjbrown** [comment]
@whikloj 👍 This has been a most educational morning. Thank you for your patience!

**Comment by whikloj** [comment]
no worries

**Comment by bryjbrown** [comment]
@ruebot Probably not, I'll most likely be adding tests as part of future PRs related to ObjectService.

**Comment by whikloj** [comment]
👍  good to go.

**Pull request merged**
