### PR TITLE
Add CONTRIBUTING badge

### PR DESCRIPTION
**Pull request by sowla**
Hi! I'm trying to address issue https://github.com/Islandora-CLAW/CLAW/issues/277 but I'm very very new to github and coding in general, so I just wanted to check I'm doing this correctly before continuing with the other repos.

Thank you for your patience! :)

### CODE REVIEW

**Comment by manez** [comment]
Hello @sowla and welcome to the CLAW project. We'll need to get a signed CLA from you in order to merge your commits (http://islandora.ca/sites/default/files/islandora_cla.pdf). This license agreement is for your protection as a contributor as well as the protection of the Foundation and its users; it does not change your rights to use your own contributions for any other purpose.

**Comment by sowla** [comment]
Sorry and thank you @ruebot and @manez! I was skim reading and missed that! I just sent the pdf :)

**Comment by manez** [comment]
CLA on file, good to go! 👍

**Comment by sowla** [comment]
Yay!! Thanks again @ruebot and @manez! :)

**Pull request merged**
